version: '3.8'
services:
  web:
    build: .
    restart: unless-stopped
    ports:
      - "5050:5050"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    extra_hosts:
      - "host.docker.internal:host-gateway"
